package org.k11techlab.framework.ai.simple;

import org.k11techlab.framework.selenium.webuitestengine.logger.Log;
import org.k11techlab.framework.ai.llm.LLMInterface;

/**
 * Simple AI client placeholder for quick testing without external dependencies.
 * This allows the framework to compile and run basic tests while you set up the full AI system.
 */
public class SimpleAIClient implements LLMInterface {
    
    private boolean enabled = false;
    
    public SimpleAIClient() {
        // Check if AI should be enabled (you can add configuration later)
        this.enabled = false;
    }
    
    /**
     * Generate a simple test suggestion
     * @param prompt The request prompt
     * @return Basic test suggestion or placeholder
     */
    public String generateSuggestion(String prompt) {
        if (!enabled) {
            return "// AI not enabled. Install Ollama and configure to use AI features\n" +
                   "// Prompt was: " + prompt;
        }
        
        // Placeholder logic for basic suggestions
        if (prompt.toLowerCase().contains("locator")) {
            return generateLocatorSuggestion(prompt);
        } else if (prompt.toLowerCase().contains("test")) {
            return generateTestSuggestion(prompt);
        } else {
            return "// AI suggestion for: " + prompt;
        }
    }
    
    private String generateLocatorSuggestion(String prompt) {
        return "// AI Locator Suggestions:\n" +
               "// 1. By.id(\"elementId\") - Use if element has stable ID\n" +
               "// 2. By.name(\"elementName\") - Use for form elements\n" +
               "// 3. By.className(\"className\") - Use for elements with semantic classes\n" +
               "// 4. By.cssSelector(\".class-name\") - Use for CSS-based selection\n" +
               "// 5. By.xpath(\"//element[@attribute='value']\") - Use as last resort";
    }
    
    private String generateTestSuggestion(String prompt) {
        return "// AI Test Suggestion:\n" +
               "@Test\n" +
               "public void testGeneratedByAI() {\n" +
               "    WebDriver driver = getDriver();\n" +
               "    // TODO: Add test steps based on: " + prompt + "\n" +
               "    \n" +
               "    // Example test structure:\n" +
               "    // 1. Navigate to page\n" +
               "    // 2. Find elements\n" +
               "    // 3. Perform actions\n" +
               "    // 4. Verify results\n" +
               "    \n" +
               "    Log.info(\"Test generated by AI for: " + prompt + "\");\n" +
               "}";
    }
    
    /**
     * Check if AI is available
     */
    public boolean isAvailable() {
        return enabled;
    }
    
    /**
     * Enable AI (when Ollama is set up)
     */
    public void enable() {
        this.enabled = true;
        Log.info("Simple AI client enabled");
    }
    
    /**
     * Get status information
     */
    public String getStatus() {
        return "Simple AI Client - Enabled: " + enabled;
    }
    
    @Override
    public String getModelInfo() {
        return "Simple AI Client - Predefined responses";
    }
    
    @Override
    public String generateResponse(String prompt) {
        return generateSuggestion(prompt);
    }
    
    @Override
    public String generateResponse(String prompt, float temperature, int maxTokens) {
        // Simple AI doesn't support parameters, use basic generation
        return generateSuggestion(prompt);
    }
    
    @Override
    public void close() {
        // Nothing to close for simple client
        Log.info("Simple AI client closed");
    }
}